name: counter_repository
description: A Dart package which manages the counter domain.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies: 
  web_socket_client: ^0.1.0-dev.3
  web_socket_counter:
    git:
      url: https://github.com/omar6260/learning-backend-from-dart-frog
      path: web_socket_counter_flutter

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
